train_data_path: 'data/preprocessed/train.txt'
valid_data_path: 'data/preprocessed/val.txt'
test_data_path: 'data/preprocessed/test.txt'
# test_data_path: /home/shahad/Downloads/multiconner/modified.txt

